### ISSUE TITLE
data issue

### ISSUE THREAD

**Issue by ccp678** [nju-websoft/LKGE#1]
Dear professor，
hello!
I have a question about your paper.
Is the data in Table 2 of your paper completed based on the synthesis of all snapshots into one dataset?
Or simply run the model in four snapshots sequentially to obtain the results.

**Comment by yncui-nju** [comment]
Hi, thank you for your interest in our work!

We train the model using newly added facts at each snapshot. The results presented in Table 2 are derived from testing the model on the test set of each snapshot after completing training on five snapshots, followed by averaging the results. It's important to note that the candidate entities for each snapshot are the entities visible in that snapshot. In other words, they are drawn from the entity set displayed in Table 1, encompassing both newly added entities in the current snapshot and entities encountered in previous snapshots.

**Comment by 17878504021** [comment]
你好 我对你们的研究课题感谢 方便询问几个问题嘛 希望能得到你帮助 加个联系方式：qq2573732030

**Comment by 17878504021** [comment]
> Dear professor， hello! I have a question about your paper. Is the data in Table 2 of your paper completed based on the synthesis of all snapshots into one dataset? Or simply run the model in four snapshots sequentially to obtain the results.

你好 方便一起探讨一下问题嘛？希望得到你的帮助
