### ISSUE TITLE
Figure 4

### ISSUE THREAD

**Issue by JiyaoWei** [nju-websoft/LKGE#2]
您好，我们想咨询一下图4（“Figure 4: Forward transfer and backward transfer of MRR.”）是怎么画出来的呢？以便引用您的工作并进一步探索，谢谢🙏

**Comment by yncui-nju** [comment]
您好，感谢对我们的工作的关注！图4所画的Forward transfer和backward transfer的计算方式在论文中有详细说明，得到数据之后，这个图是用PPT画的图表拼起来的。希望对您的工作有所帮助！

**Comment by JiyaoWei** [comment]
非常感谢！
